default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: articles-comments-425_development

test:
  <<: *default
  database: articles-comments-425_test
